### ISSUE TITLE
mysql database For securitY -to secure the connections/entries

### ISSUE THREAD

**Issue by msebastian100** [1Remote/PRemoteM#245]
Hello,
I love the software 
Would it be possible to add a function to connect to a mysql database?
That would be very practical for security.
Of course you can also save a backup file (Exempel.prma) but still Mysql would be great :)

Greetings Sebastian Mallach

**Comment by VShawn** [comment]
Hi thanks for the advice. AND YES I have been thinking about multi data source for years, MySQL of course is under consideration. 
But I don't need a MySQL database in my daily use. And any demand I personally don't need is a low priority demand I think, and low priority demand will be delayed since I am the only developer in this project.

But it will be implemented one day, I have created the folder structure for this :)

https://github.com/1Remote/PRemoteM/tree/dev_net6/Ui/Model/DAO

**Comment by majkinetor** [comment]
I think this is overkill. This makes sense only for hard core corporate use and as such I would totally give it low priority. You would also have to make an migration from sqlite to mysql. And why MySql? PostgreSQL seems like better fit TBH given that its not owned by Oracle overlords. I don't see how this relates to security either.

**Comment by VShawn** [comment]
IMO this has nothing to do with security, it just giving you an alternative. 

With mysql we can share servers in a team: sending json file to share servers just annoying us in my ofice.

BTW I never thought about the migration from sqlite to mysql. User must export json file from sqlite  then import to mysql manully in my design. 

In the end I want to reiterate that it is a vervy low priority demand for me. Development fot this will not start in the near future
