### ISSUE TITLE
add rdp:// URI handler

### ISSUE THREAD

**Issue by emtek-at** [1Remote/PRemoteM#274]
No Problem, just a wish :-)

**Describe the solution you'd like**
It would be nice if I could open a rdp:// uri with premotem, because of the very good RDP Screen sizing capabilities.

So, please add a uri handler.

best regards

**Comment by VShawn** [comment]
I've never heard of it. Can you show us how `rdp:// uri` wroks?

**Comment by VShawn** [comment]
I see `rdp://` is not an official protocol, Right?

from 

https://github.com/konradsikorski/RdpProtocolHandler/blob/master/RdpProtocolHandler/Program.cs#L121-L154

It needs AdministratorPrivilages to register a URL Protocol to the registry, so that the windows can call the too with start rdp parameter when it open uri which start with rdp:// using browser.


I don't see much benefit for integrating `rdp:// uri` since we start sessions from the launcher.
