### ISSUE TITLE
Error [(<OnUIThreadSync>b__0:0)]	

### ISSUE THREAD

**Issue by stetze88** [1Remote/PRemoteM#306]
[T:001][18:25:55.841]	`Error`		[(<OnUIThreadSync>b__0:0)]	
> System.Runtime.InteropServices.COMException (0x8000FFFF): Schwerwiegender Fehler (Ausnahme von HRESULT: 0x8000FFFF (E_UNEXPECTED))
   bei MSTSCLib.IMsRdpClient9.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
   bei PRM.View.Host.ProtocolHosts.AxMsRdpClient09Host.<>c__DisplayClass49_0.<SetRdpResolution>b__0() in D:\DemoProject\PRemoteM-NET6\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:Zeile 753.

> StackTrace:    bei MSTSCLib.IMsRdpClient9.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
   bei PRM.View.Host.ProtocolHosts.AxMsRdpClient09Host.<>c__DisplayClass49_0.<SetRdpResolution>b__0() in D:\DemoProject\PRemoteM-NET6\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:Zeile 753.

**Comment by majkinetor** [comment]
Pending delition.

**Comment by VShawn** [comment]
> bei MSTSCLib.IMsRdpClient9.UpdateSessionDisplaySettings(UInt32 ulDesktopWidth, UInt32 ulDesktopHeight, UInt32 ulPhysicalWidth, UInt32 ulPhysicalHeight, UInt32 ulOrientation, UInt32 ulDesktopScaleFactor, UInt32 ulDeviceScaleFactor)
bei PRM.View.Host.ProtocolHosts.AxMsRdpClient09Host.<>c__DisplayClass49_0.b__0() in D:\DemoProject\PRemoteM-NET6\Ui\View\Host\ProtocolHosts\AxMsRdpClient09Host.xaml.cs:Zeile 753.

so it die here:

https://github.com/1Remote/PRemoteM/blob/dev_net6/Ui/View/Host/ProtocolHosts/AxMsRdpClient09Host.xaml.cs#L741-L760

I dont think an assignment statement at line 753 will throw a COMException...

And since a try block here, exception should have be catched...

I have no idea how to fix this ticket based on current information.

> Pending delition.

@majkinetor 

hey, what's that? you mean deletion?

**Comment by majkinetor** [comment]
Yeah, this ticket is rude.
